# Generated by Django 5.2.8 on 2025-11-12 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npi_number', models.CharField(max_length=20, unique=True)),
                ('enumeration_type', models.CharField(blank=True, max_length=30)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('organization_name', models.CharField(blank=True, max_length=100)),
                ('address_purpose', models.CharField(blank=True, max_length=50)),
                ('address_line', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=10)),
                ('postal_code', models.CharField(blank=True, max_length=15)),
                ('country_code', models.CharField(blank=True, max_length=10)),
                ('telephone_number', models.CharField(blank=True, max_length=30)),
                ('fax_number', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'db_table': 'provider',
            },
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxonomy_code', models.CharField(max_length=10, unique=True)),
                ('taxonomy_classification', models.CharField(blank=True, max_length=255)),
                ('taxonomy_specialization', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'taxonomy',
            },
        ),
        migrations.CreateModel(
            name='ProviderTaxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.provider')),
                ('taxonomy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.taxonomy')),
            ],
            options={
                'db_table': 'provider_taxonomy',
            },
        ),
    ]
