# Generated by Django 5.2.8 on 2025-11-13 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='country_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='provider',
            name='fax_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='provider',
            name='postal_code',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='provider',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='provider',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
