# Generated by Django 5.2.8 on 2025-11-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_alter_provider_country_code_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['first_name'], name='provider_first_n_b1aa86_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['last_name'], name='provider_last_na_a5e927_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['organization_name'], name='provider_organiz_55ec6d_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['npi_number'], name='provider_npi_num_610c99_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['address_line'], name='provider_address_c7db97_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['city'], name='provider_city_2bd140_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['state'], name='provider_state_e379ad_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['postal_code'], name='provider_postal__ad1ff0_idx'),
        ),
    ]
