# Generated by Django 5.2.8 on 2025-11-13 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_provider_provider_first_n_b1aa86_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='providertaxonomy',
            table=None,
        ),
        migrations.AlterModelTable(
            name='taxonomy',
            table=None,
        ),
    ]
